### ISSUE TITLE
Not able generate the Genesis # for Private network

### ISSUE THREAD

**Issue by devSpeqto** [bnb-chain/bsc-genesis-contract#117]
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genesis-contracts@1.0.0 generate-testnet script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-11-30T12_12_25_409Z-debug.log

**Comment by zjubfd** [comment]
close stale issue
