### ISSUE TITLE
[HELP] Don't understand where to get top 21 staking validators

### ISSUE THREAD

**Issue by linrium** [bnb-chain/bsc-genesis-contract#173]
I checked the source code of the BSCValidatorSet. But I don't see where you get the top 21 staking validators. And I don't understand you need to shuffle twice when call `getMiningValidators`. Could you help me explained it? Thank you.
https://github.com/bnb-chain/bsc-genesis-contract/blob/7100748eecd9ee56203d36e957e72a2774eaa40d/contracts/BSCValidatorSet.sol

**Comment by zjubfd** [comment]
This is well explained in https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP131.md
