### ISSUE TITLE
tenor

### ISSUE THREAD

**Issue by quinio01** [bnb-chain/bsc-genesis-contract#178]
Phrase storage

**Comment by quinio01** [comment]
> Phrase storage

@quinio01 @guagualvcha - [ ] - - # @Loverush @quinio01 ~~[]- ()_https://www.binance.me/en/activity/referral/offers/claim?ref=CPA_00R1IB3NNG_~~

**Comment by quinio01** [comment]
command

**Comment by acellimitz** [comment]
I deposit so many but my wallet is 0 already so how I withdrawal in a free way to get it quickly?
