### ISSUE TITLE
My trustwallet

### ISSUE THREAD

**Issue by quinio01** [bnb-chain/bsc-genesis-contract#179]
My Public Address to Receive TWT 0x5dE5C70BF7048CFCFc4b6dDb08cB4ebd53943626

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=20000714&address=0x5dE5C70BF7048CFCFc4b6dDb08cB4ebd53943626&token_id=0x4B0F1812e5Df2A09796481Ff14017e6005508003
@quinio01

**Comment by Chukwulawrence** [comment]
@quinio01 We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5
