### ISSUE TITLE
Use Local Memory Type Variable Instead of Global Storage Type Variable in Event to Save Gas

### ISSUE THREAD

**Issue by HighBe** [bnb-chain/bsc-genesis-contract#182]
Hi, we recently have conducted a systematic study about Solidity event usage, evolution, and impact, and we are attempting to build a tool to improve the practice of Solidity event use based on our findings. We have tried our prototype tool on some of the most popular GitHub Solidity repositories, and for your repository, we find a potential optimization of gas consumption arisen from event use.  

The point is that when we use emit operation to store the value of a certain variable, local memory type variable would be preferable to global storage type (state) variable if they hold the same value. The reason is that an extra SLOAD operation would be needed to access the variable if it is storage type, and the SLOAD operation costs 800 gas.

For your repository, we find that the following event use can be improved:

- [TendermintLightClient.sol](https://github.com/bnb-chain/bsc-genesis-contract/blob/master/contracts/TendermintLightClient.sol)
**function name:**&emsp;*init*
**event name:**&emsp;&emsp;*initConsensusState*
**variable:**&emsp;&emsp;&emsp;&emsp;*initialHeight->height*

```Solidity
  function init() external onlyNotInit {
    uint256 pointer;
    uint256 length;
    (pointer, length) = Memory.fromBytes(INIT_CONSENSUS_STATE_BYTES);

    /* solium-disable-next-line */
    assembly {
      sstore(chainID_slot, mload(pointer))
    }

    ConsensusState memory cs;
    uint64 height;
    (cs, height) = decodeConsensusState(pointer, length, false);
    cs.preValidatorSetChangeHeight = 0;
    lightClientConsensusStates[height] = cs;

    initialHeight = height;
    latestHeight = height;
    alreadyInit = true;
    rewardForValidatorSetChange = INIT_REWARD_FOR_VALIDATOR_SER_CHANGE;

    emit initConsensusState(initialHeight, cs.appHash);
  }
```

Do you find our results useful? Your reply and invaluable suggestions would be greatly appreciated, and are vital for improving our tool. Thanks a lot for your time!

**Comment by acellimitz** [comment]
I cannot understand please help me to explain for what this is mean

**Comment by HighBe** [comment]
> I cannot understand please help me to explain for what this is mean

Thanks a lot for your reply. The point (to us) is after compiling the event use to EVM bytecode, an extra Sload EVM operation would be needed to access the variable if it is storage type, and the Sload operation costs 800 gas since it deals with data in Storage area. Thus, when we use event to store the value of a certain variable in transaction log, local memory type variable would be preferable to storage type variable if they hold the same value.
