### ISSUE TITLE
Wallet extension 

### ISSUE THREAD

**Issue by Jellyman447** [bnb-chain/bsc-genesis-contract#234]
1273532938$paystring.crypto.com

**Comment by hamzawajahat** [comment]
> 

Yes bro

**Comment by Jellyman447** [comment]
Ok

**Comment by Jellyman447** [comment]
Welcome you all ,to an endpoint extension of this project

**Comment by Jellyman447** [comment]
That's good feedback

**Comment by Jellyman447** [comment]
Redirection to an endpoint extension will be very important for security standard protection
