### ISSUE TITLE
Display Bug From Any Mainnet To BNB Chain

### ISSUE THREAD

**Issue by SamKing26** [bnb-chain/bsc-genesis-contract#257]
When you change mainnet to bnb chain at metamask the token always bug

https://user-images.githubusercontent.com/128742970/230309430-cccc1333-e95d-4281-9d22-82130d3fb5b0.mp4

**Comment by isaacyuno** [comment]
Sorry can't see the where is the bug? Which RPC are you using? Do you have a video in English?

**Comment by SamKing26** [comment]
@isaacyuno idk either if its bug or only glitch, i just found it when i was gonna claim an airdrop on my old wallet ,but something that i know if its glitch should be happend on all mainnet but its only work on bnb mainnet
