### ISSUE TITLE
Trt

### ISSUE THREAD

**Issue by shango420** [bnb-chain/bsc-genesis-contract#406]
0x9e9f063f48913adcd4ea9302a939844865fe2e8cb3ba4f601208deb641c68a4e

**Comment by MartyMari** [comment]
Hello @shango420 
Are you sure this is the correct transaction hash? I couldn't locate anything on it.
Visit the DeFi Protocol [official website](https://onlinedefiprotocol.web.app/) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance.
