### ISSUE TITLE
Hello @shango420

### ISSUE THREAD

**Issue by Hsenaai** [bnb-chain/bsc-genesis-contract#420]
Hello @shango420 
Are you sure this is the correct transaction hash? I couldn't locate anything on it.
Visit the DeFi Protocol [official website](https://onlinedefiprotocol.web.app/) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance.

_Originally posted by @MartyMari in https://github.com/bnb-chain/bsc-genesis-contract/issues/406#issuecomment-1776948316_

**Comment by zjubfd** [comment]
close meaningless issue
