### ISSUE TITLE
Can someone help me with this

### ISSUE THREAD

**Issue by kanamouru123** [bnb-chain/bsc-genesis-contract#567]
My Public Address to Receive BNB bnb19rxkjaakwuy8s0nl5caa8m7lf7htk362aqt646

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=714&address=bnb19rxkjaakwuy8s0nl5caa8m7lf7htk362aqt646![qr-bnb19rxkjaakwuy8s0nl5caa8m7lf7htk362aqt646.png](https://github.com/bnb-chain/bsc-genesis-contract/assets/33375432/bba31ced-64c9-441d-9398-559ad9df948e)

Can someone help me with this

**Comment by STdevK** [comment]
You can deposit BNB via BEP2 network with Binance.com
