### ISSUE TITLE
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328

### ISSUE THREAD

**Issue by MoharshBoru** [bnb-chain/bsc-genesis-contract#582]
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328

_Originally posted by @Chator1 in https://github.com/bnb-chain/bsc-genesis-contract/issues/581#issuecomment-2250881552_

**Comment by malibb341** [comment]
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328
